language: php

services:
  - mongodb

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev --prefer-source

script:
  - ./vendor/bin/phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm